### ISSUE TITLE
MOSFET model bugs

### ISSUE THREAD

**Issue by harrybu** [knowm/jspice#1]
[https://github.com/knowm/jspice/blob/master/src/main/java/org/knowm/jspice/component/element/nonlinear/MOSFET.java](url)
The method attemptToDetermineVgs() is called with the wrong node IDs: node[1] instead of node[2] for source node.
The CMOSInverter circuits do not show the correct expected behavior like in the README.md. The DCSweep looks exactly like PMOS and NMOS inverter. Transient Analysis of CMOSInverter shows a massively high overswing at the border from high to low and vice versa.

**Comment by timmolter** [comment]
Thanks for the bug report. I'll look into it.

**Comment by timmolter** [comment]
Fixed. It was mostly an issue with my DC operation point code.
